#! /bin/bash

#read -p "Please, Enter your character:" val
val=$1
if [  $# -eq 0  ]
then
	echo "Nothing"
	exit 1
fi


case "$val" in
  [[:upper:]])
		echo "Upper Case"
		;;
  [[:lower:]])
		echo "Lower Case"
		;;
  [[:digit:]])
		echo "Number"
		;;
  *)
               echo "Mix"
		;;
esac

  	
